# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-11 10:06
from __future__ import unicode_literals

import account.utils
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric or contain any of the following:". @ + -" ', regex='^[a-zA-z0-9.+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_receptionist', models.BooleanField(default=False)),
                ('is_cashier', models.BooleanField(default=False)),
                ('is_medical', models.BooleanField(default=False)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=account.utils.code_generator, max_length=120)),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('Phone_no', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('department', models.CharField(choices=[('ENT', 'ENT'), ('EYE', 'EYE'), ('BONE', 'BONE'), ('Others', 'Others')], default=None, max_length=50)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('preffered_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Nepal', max_length=150)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
                ('specialist', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Patient_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=250)),
                ('comments', models.TextField(max_length=250)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Patient_Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(max_length=1000)),
                ('comments', models.TextField(max_length=1000)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=250)),
                ('result', models.TextField()),
                ('test_date', models.DateTimeField(default=datetime.datetime.now)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Test_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.BooleanField(default=False)),
                ('test_name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('test_date', models.DateTimeField(default=datetime.datetime.now)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Meds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
                ('p_date', models.DateTimeField(default=datetime.datetime.now)),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Medical')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, default=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Receptionist'),
        ),
        migrations.AddField(
            model_name='medical_meds',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient'),
        ),
        migrations.AddField(
            model_name='lab_test_bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient'),
        ),
        migrations.AddField(
            model_name='lab_test',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labtests', to='account.Patient'),
        ),
        migrations.AddField(
            model_name='doctor_patient_med',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient'),
        ),
        migrations.AddField(
            model_name='doctor_patient_lab',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient'),
        ),
    ]
