# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-11 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 11, 10, 30, 2, 252882, tzinfo=utc), null=True),
        ),
    ]
