# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-13 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190211_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_patient_lab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 13, 9, 10, 23, 95541, tzinfo=utc), null=True),
        ),
    ]
