# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190213_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 14, 6, 10, 35, 8097, tzinfo=utc), null=True),
        ),
    ]
