# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190216_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 25, 12, 21, 46, 775178, tzinfo=utc), null=True),
        ),
    ]
