# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-25 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190325_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 25, 12, 27, 59, 68448, tzinfo=utc), null=True),
        ),
    ]
