# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190325_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 26, 7, 31, 0, 291713, tzinfo=utc), null=True),
        ),
    ]
