# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-26 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190326_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_patient_med',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 26, 7, 33, 12, 762276, tzinfo=utc), null=True),
        ),
    ]
